CREATE SERVER AUDIT BackupRestoreAudit TO EXTERNAL_MONITOR;
GO

CREATE SERVER AUDIT SPECIFICATION BackupRestoreAuditSpec
FOR SERVER AUDIT BackupRestoreAudit
ADD (BACKUP_RESTORE_GROUP),
ADD (AUDIT_CHANGE_GROUP)
WITH (STATE=ON);

ALTER SERVER AUDIT BackupRestoreAudit WITH (STATE=ON);
GO
